// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHQCaAieGdZG0OYRI321X1wkuin85wYZM',
    appId: '1:891631910173:web:d98becfef73edb15d0b5f4',
    messagingSenderId: '891631910173',
    projectId: 'mobdev-finals-1d81a',
    authDomain: 'mobdev-finals-1d81a.firebaseapp.com',
    storageBucket: 'mobdev-finals-1d81a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOJzCvBki6UwlQJ0m9LgQU7VQEWbG6Pbo',
    appId: '1:891631910173:android:c601a8dc39788e92d0b5f4',
    messagingSenderId: '891631910173',
    projectId: 'mobdev-finals-1d81a',
    storageBucket: 'mobdev-finals-1d81a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9Gz0e_sTdqWsjHRp7X4QHDDNhcn3qfk',
    appId: '1:891631910173:ios:b9cf3b5b4dc3483bd0b5f4',
    messagingSenderId: '891631910173',
    projectId: 'mobdev-finals-1d81a',
    storageBucket: 'mobdev-finals-1d81a.appspot.com',
    iosBundleId: 'com.example.mobdevFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP9Gz0e_sTdqWsjHRp7X4QHDDNhcn3qfk',
    appId: '1:891631910173:ios:c4a30aa2ab9535f1d0b5f4',
    messagingSenderId: '891631910173',
    projectId: 'mobdev-finals-1d81a',
    storageBucket: 'mobdev-finals-1d81a.appspot.com',
    iosBundleId: 'com.example.mobdevFinal.RunnerTests',
  );
}
